# Generated by Django 4.0.3 on 2022-04-27 13:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loja', '0003_livro_destaque'),
    ]

    operations = [
        migrations.AddField(
            model_name='livro',
            name='numero_avaliacoes',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='livro',
            name='avaliacao_livro',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=7),
        ),
    ]
