# Generated by Django 4.0.3 on 2022-04-27 13:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loja', '0004_livro_numero_avaliacoes_alter_livro_avaliacao_livro'),
    ]

    operations = [
        migrations.AlterField(
            model_name='livro',
            name='sinopse',
            field=models.TextField(blank=True, max_length=255, null=True),
        ),
    ]
