# Generated by Django 4.0.3 on 2022-04-27 16:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loja', '0006_livro_excerto_alter_livro_sinopse'),
    ]

    operations = [
        migrations.AddField(
            model_name='livro',
            name='ativo',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='livro',
            name='excerto',
            field=models.TextField(blank=True, max_length=200, null=True),
        ),
    ]
