# Generated by Django 4.0.3 on 2022-04-28 12:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loja', '0009_alter_carrinho_frete_alter_carrinho_subtotal_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='carrinho',
            name='n_itens',
            field=models.IntegerField(default=0),
        ),
    ]
