# Generated by Django 4.0.3 on 2022-04-28 14:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loja', '0010_carrinho_n_itens'),
    ]

    operations = [
        migrations.AddField(
            model_name='carrinho',
            name='frete_gratis',
            field=models.BooleanField(default=False),
        ),
    ]
