# Generated by Django 4.0.3 on 2022-04-28 14:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loja', '0011_carrinho_frete_gratis'),
    ]

    operations = [
        migrations.AddField(
            model_name='dadosuser',
            name='estado',
            field=models.CharField(blank=True, max_length=2, null=True),
        ),
        migrations.AddField(
            model_name='dadosuser',
            name='municipio',
            field=models.CharField(blank=True, max_length=80, null=True),
        ),
    ]
