# Generated by Django 4.0.3 on 2022-04-28 16:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loja', '0012_dadosuser_estado_dadosuser_municipio'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dadosuser',
            name='bairro',
            field=models.CharField(max_length=80),
        ),
        migrations.AlterField(
            model_name='dadosuser',
            name='cep',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='dadosuser',
            name='estado',
            field=models.CharField(max_length=2),
        ),
        migrations.AlterField(
            model_name='dadosuser',
            name='municipio',
            field=models.CharField(max_length=80),
        ),
        migrations.AlterField(
            model_name='dadosuser',
            name='numero',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='dadosuser',
            name='rua',
            field=models.CharField(max_length=150),
        ),
        migrations.AlterField(
            model_name='dadosuser',
            name='telefone',
            field=models.CharField(max_length=20),
        ),
    ]
