# Generated by Django 4.0.3 on 2022-04-28 16:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loja', '0013_alter_dadosuser_bairro_alter_dadosuser_cep_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='dadosuser',
            name='nome',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
