# Generated by Django 4.0.3 on 2022-04-28 17:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('loja', '0016_alter_carrinho_entrega'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='carrinho',
            name='entrega',
        ),
    ]
