# Generated by Django 4.0.3 on 2022-04-28 17:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('loja', '0017_remove_carrinho_entrega'),
    ]

    operations = [
        migrations.AddField(
            model_name='carrinho',
            name='entrega',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='loja.dadosuser'),
        ),
    ]
