# Generated by Django 4.0.3 on 2022-04-28 19:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loja', '0022_livro_quantidades_vendidas'),
    ]

    operations = [
        migrations.AlterField(
            model_name='livro',
            name='quantidades_vendidas',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
