# Generated by Django 4.0.3 on 2022-04-28 20:06

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('loja', '0023_alter_livro_quantidades_vendidas'),
    ]

    operations = [
        migrations.AddField(
            model_name='pedido',
            name='data',
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
